### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by frostfire48** [hackrobotman/Nitrox-2.0#1]
Hello, I have the build 59783 but it doesn't seem to work, do you have any idea ?
I was able to do every step. Once you edit the line "steam....0202" , do you compile, save it and run again the launcher ? Is there an additional step to do ?
Because I'm able to launch the game with multiplayer button, but it still displays soloplayer menu.

EDIT1: I found out the updates to go to v60026 (Update 84 and 85) and I'll try again. I also tried with the most recent version of the game (v63112; 63461; 63668) but it didn't work.

EDIT2: This time I tried with v60026 build (after update 85). The game does not launch with the multiplayer. I edited the "steam_emu" file and with the same steam ID as used before in the previous steps (maybe it is obvious for some people). 
And now it is launching the multiplayer menu when I start the game from Subnautica.exe ! 

Thanks for bringing it to cracked version anyway :)

**Comment by hackrobotman** [comment]
Wait so does it work or not I don’t understand? Also are you using 32-bit dnSpy? If its not still not working download the original mod and in dnSpy open NitroxModel.dll > NitroxModel > Helper > PirateDetection.cs find the method that checks your steamapi_64.dll for length and change it to return false. That’s from memory the exact path to PirateDetection might be wrong.

**Comment by hackrobotman** [comment]
Also please feel free to spread the word about this updated version of Nitrox

**Comment by frostfire48** [comment]
It's working , I'm playing right now with a friend using a legit steam version with another version (61026 I think). 
But to make it work I have to first click on multiplayer in nitrox launcher (nothing happens visually) then I can launch subnautica.exe in the game folder. Otherwise, only the single player mode is available 
![image](https://user-images.githubusercontent.com/60841871/74280163-84c2bf80-4d1c-11ea-9801-d3923b6bec49.png)

Thanks again !

**Comment by hackrobotman** [comment]
Weird clicking play multiplayer should launch subnautica. Anyway it sounds like you’ve successfully bootstrapped nitrox to your subnautica install so you’re good to go. Try running the steamapp://run/GAME-ID command in the run menu (Win+R). This requires subnautica being added to steam as a non steam game as in the first few steps of the readme. If the command doesn’t work subnautica isn’t added to steam correctly or the GAME-ID is wrong. You could also replace the line with the direct path to subnautica.exe as I believe that string is directly inserted into Win+R through the mod. Not sure about that tho

**Comment by frostfire48** [comment]
> 
> 
_Also are you using 32-bit dnSpy?_ Yes
 _If its not still not working download the original mod and in dnSpy open NitroxModel.dll > NitroxModel > Helper > PirateDetection.cs find the method that checks your steamapi_64.dll for length and change it to return false. That’s from memory the exact path to PirateDetection might be wrong._ 
I tried to modify it but compiling after was buggy

**Comment by hackrobotman** [comment]
How was it buggy? Also my buddy had trouble w my method but I walked him through directly modifying the original mod so that PirateDetection would return false and StartSubnautica would have the correct ID, and it worked compiled without issue. However it only compiled with 32-bit dnSpy. 64-Bit would through Compiler errors. If you’re having trouble referencing certain elements in the source code, try adding assembly references to appropriate .dll files. This could break it tho. If nothing is compiling try downloading the original mod, opening NitroxLauncher.exe in 32-bit dnSpy and click edit class on LauncherLogic, and see if it can compile WITHOUT actually editing it. If it doesn’t compile, lmk what your errors are.

**Comment by hackrobotman** [comment]
*throw

**Comment by frostfire48** [comment]
> steamapp://run/GAME-ID

For the GAME-ID , do you use the official one ? (264710) 

When I run the command , I have this 
![image](https://user-images.githubusercontent.com/60841871/74319232-e156c680-4d7e-11ea-89d2-0d3a960c0080.png)
So I guess it is not working properly.  I did add the game as a non steam game as described and I can see it in my game list but when I launch it in steam, it is only the single player mode.

**Comment by frostfire48** [comment]
And replacing the path of subnautica.exe directly doesn't work. I can't compile
![image](https://user-images.githubusercontent.com/60841871/74319600-8376ae80-4d7f-11ea-8016-ea68f6341b50.png)

**Comment by frostfire48** [comment]
PirateDetection is already returning false, is there a line to change?
![image](https://user-images.githubusercontent.com/60841871/74320206-802ff280-4d80-11ea-9ce0-e1f4cd4a9036.png)

**Comment by hackrobotman** [comment]
I made a typo when earlier. It should be "steam://rungameid/GAME-ID"
Anyway I am a bit confused about what exactly is going wrong so lets do this from the beginning.

1. Did you follow the readme exactly? If not, what steps did you do differently?
2. When you try to play multiplayer with Subnautica, what exactly is going wrong?

I have since removed the AssetBundles-lib.zip file and replaced it with the extracted version. I'd recommend downloading this repo again and following the readme instructions exactly if you still care to fix whatever issue you have. You should extract that folder if you still have it.

**Comment by frostfire48** [comment]
Hello , 
1. Yes I did follow every step. Then I compile, save NitroxLauncher.exe and close dnspy.
2. When I launch NitroxLauncher.exe , I press "play multiplayer" but the game isn't starting. However, after when I launch subnautica.exe or steam://rungameid/GAME-ID , it is launching the game with multiplayer in the main menu

**Comment by hackrobotman** [comment]
I recently updated the files in this repo so please check to see if you have an AssetBundles-lib.zip folder in your Nitrox folder. If you do, extract it. It doesn’t sound like the issue is related to that though. Try replacing the line in the StartSubnautica method with the path to subnautica.exe. Make sure the path is in quotes.

Honestly though if you have the multiplayer button and you’re able to play multiplayer, then it’s a weird bug that it wont launch but it doesn’t really affect play. If that’s the case and the fixes above don’t fix your issue, I’m inclined to close it bc it’s more quality of life than performance-affecting

**Comment by frostfire48** [comment]
I do have the AssetBundles-lib.zip and I extracted it in the beginning so nothing to do about that unfortunately. 
_Try replacing the line in the StartSubnautica method with the path to subnautica.exe. Make sure the path is in quotes._
I did that too but I can't compile the method
